language: d
sudo: false

script:
  - ./ci.sh

matrix:
    include:
        - d: dmd-2.079.0
        - d: dmd-2.078.3
        - d: dmd-2.077.1
        - d: ldc-1.8.0
        - d: ldc-1.7.0
        - d: ldc-1.6.0
