name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        dc:
          - dmd-2.100.2
          - ldc-1.30.0

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1.2.1
        with:
          compiler: ${{ matrix.dc }}

      - name: Run tests
        shell: bash
        run: ./ci.sh

      - uses: codecov/codecov-action@v3.1.1
